# Generated by Django 4.0.6 on 2022-07-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='econtact',
            new_name='eContact',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eid',
            new_name='eId',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='eName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eemail',
            new_name='email',
        ),
    ]
